#!/usr/bin/env bash
# a Bash script that cleans up a directory by organizing
#+ files into subdirectories based on their file extensions.
# with dynamical directory creation

# read input from user
read -rp "Input Directory Path: " parent_dir
echo "$parent_dir"
if [ ! -d "$parent_dir" ];then
echo "Not a valid Directory"

else
for file in "$parent_dir"/*;do
        echo "$file"
        if [ -f "$file" ] && [ ! -x "$file" ];then
		if [ -s $file ]; then
                 extension=$(file -mime-type "$file" | cut -d '/' -f2)
		else
		 extension=${file##*.}
		fi
                echo "$extension"
                dir="$parent_dir/$extension"
                if [ ! -d "$dir" ];then
                mkdir -p "$dir"
                fi
		mv "$file" "$dir/"
        fi


done
echo "Directory succesfully cleaned!!"
fi

